# GitHub Pages configuration
baseurl: "/sva-pages"
url: "https://tonnguyen.github.io"

# Enable Jekyll processing
markdown: kramdown
highlighter: rouge

# Don't process Jekyll files
include: []
exclude: []

# Serve static files correctly
plugins: []
